development:
  adapter: postgresql
  encoding: unicode
  database: super_development
  pool: 5
  username:
  password:
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: super_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: super_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test
